out/production/Training Org Avenga/objects/Client__c.object
<CustomObject>
    <description>The person who buys services of the company</description>
    <label>Client</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Developer__c.object
<CustomObject>
    <description>The person who gets the job done</description>
    <fields>
        <fullName>Is_Billable__c</fullName>
        <description>if Dev has at least one billable project assigned - green image, else - yellow</description>
        <formula>IF(Total_Billable_Projects__c &gt;0,IMAGE(&quot;/resource/Green&quot;,&quot;Green&quot;,20,20),IMAGE(&quot;/resource/Yellow&quot;,&quot;Yellow&quot;,20,20))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Billable?</label>
        <type>Text</type>
    </fields>
    <label>Developer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project__c.object
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>defines if the project is active</description>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The client who owns the project</description>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>defines if the project is billable (it happens)</description>
        <label>Is Billable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Budget__c</fullName>
        <description>project budget</description>
        <label>Project Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <description>dev</description>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>only active projects may be assigned</description>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Project Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000}</displayFormat>
        <label>Project Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Training Org Avenga/src/classes/ItCompanyServices.cls
public with sharing class ItCompanyServices {
    public static Database.SaveResult createProject(Id clientId) {

        Database.SaveResult saveResult = Database.insert(new Project__c(Client__c = clientId));

        return saveResult;
    }
        //__________________________________________________________________________________________________________________
    public static void createProjectAssignment(Id projectId, Id developerId) {
        try {
            insert (new Project_Assignment__c(Project__c = projectId, Developer__c = developerId));
        } catch (DmlException e) {
            System.debug('Error = ' + e);
        }
    }
        //__________________________________________________________________________________________________________________
    public static void makeProjectBillable(Id projectId) {
        Project__c project = new Project__c(Id = projectId);
        project.Is_Billable__c = true;
        project.Project_Budget__c = 20;
        try {
            update project;
        } catch (DmlException e) {
            System.debug('Error = ' + e);
        }

    }
        //__________________________________________________________________________________________________________________
    public static void deactivateProjects(Set<Id> projectIds) {
        List <Project__c> listProjects = new List<Project__c>();

        for (Id projectId : projectIds) {
            Project__c project = new Project__c(Id = projectId);
            project.Active__c = false;
            listProjects.add(project);
        }

        List<Project_Assignment__c> listProjectAssignments = [SELECT Id FROM Project_Assignment__c WHERE Project__c IN :projectIds];

        try {
            update listProjects;
            delete listProjectAssignments;
        } catch (DmlException e) {
            System.debug('Error = ' + e);
        }
    }
    //For check
//    Set<Id> projectIds  = new Set<Id>{'a027Q0000039ApN','a027Q0000039AqA','a027Q0000039AqF','a027Q0000039AqK'};
//
//    ItCompanyServices.deactivateProjects(projectIds);
        //__________________________________________________________________________________________________________________
    public static List<Database.SaveResult> createDeveloperAndAssign(String devName, Set<Id> projectIds) {
        Developer__c developer = new Developer__c(Name = devName);
        Database.SaveResult developerInsert = Database.insert (developer,false);

        Id developerId = developer.Id;

        List <Project_Assignment__c> listNewProjectAssignments = new List<Project_Assignment__c>();

        for (Id projectId : projectIds) {
            Project_Assignment__c assignment = new Project_Assignment__c(
                    Developer__c = developerId,
                    Project__c = projectId);
            listNewProjectAssignments.add(assignment);
        }

        List<Database.SaveResult> projectAssignmentInsert = Database.insert(listNewProjectAssignments);
       // projectAssignmentInsert.add(0, developerInsert);

        return projectAssignmentInsert;
    }

    //Checking
    // Set<Id> projectIds  = new Set<Id>{'a027Q0000039AqyQAE'};
    //
    //ItCompanyServices.createDeveloperAndAssign('NewDew',projectIds);


}
/*
Method name                 |Result type	            |Input parameters                   |	Description
+ createProject	            | Database.SaveResult	    |Id clientId	                    | create project
+ createProjectAssignment     |void	                    |Id projectId, Id developerId	    |create project assignment
+ makeProjectBillable         |	void                    |	Id projectId	                |update project with IsBillable__c = true
+deactivateProjects          |	void	                |Set<Id> projectIds	                |update project with Active__c = false, delete all project assignments
+createDeveloperAndAssign *	|List<Database.SaveResult>	|String devName, Set<Id> projectIds|	create Developer record and assign projects to it
 */