out/production/Training Org Avenga/objects/Client__c.object
<CustomObject>
    <description>The person who buys services of the company</description>
    <label>Client</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Developer__c.object
<CustomObject>
    <description>The person who gets the job done</description>
    <fields>
        <fullName>Total_Billable_Projects__c</fullName>
        <description>Total number of active and billable projects</description>
        <label>Total Billable Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Developer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <description>dev</description>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Project Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000}</displayFormat>
        <label>Project Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Training Org Avenga/src/classes/ItCompanyDAO.cls
public with sharing class ItCompanyDAO {

 /*   getAvailableDeveloperIds |	Set<Id>	| -	|get developer ids who has assigned less then into 5
    billable projects (use Developer__c.Total_Billable_Projects__c field))
  */
    public static Set<Id> getAvailableDeveloperIds(){

        Set<Id> ids = new Set<Id>();
        
        List<Developer__c> listDevelopers = 
        [SELECT Id FROM Developer__c WHERE Developer__c.Total_Billable_Projects__c < 5];
            for(Developer__c developer : listDevelopers){
                ids.add(developer.Id);
            }
        return ids; 
    }

   // Task : getUnassignedDeveloperIds |	Set<Id>	| -	| get developer ids who has assigned into 0 projects
    public static Set<Id> getUnassignedDeveloperIds(){

        //Creating List of developers without any related projects
        List<Developer__c> listAllDevelopers = [SELECT Id, Name FROM Developer__c
        WHERE Id NOT IN (SELECT Developer__c FROM Project_Assignment__c)];

        return  (new Map<Id,Developer__c>(listAllDevelopers)).keySet();
    }
}

/*Method name	| Result type  |	Input parameters |	Description

getClients |	List<Client__c>	| Integer limitNumber, Integer offsetNumber	| get Client__c records
 with LIMIT and OFFSET

getDevelopers |	List<Developer__c>	| Set<Id> developerId, Integer limitNumber, Integer offsetNumber	|
dynamic query. If any of params is null - do not add respective condition to query.

getClientTotalActiveProjects	| Map<Id, Integer>	| Set<Id> clientIds	| return map, where key = client id, 
value = number of active projects.

getDeveloperTotalBillableProjects |	Map<Id, Integer>	| Set<Id> developerIds	| return map, where key = developer id, 
value = number of billable assigned projects.
*/