out/production/Training Org Avenga/objects/Developer__c.object
<CustomObject>
    <description>The person who gets the job done</description>
    <label>Developer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project__c.object
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

out/production/Training Org Avenga/objects/Project_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <description>dev</description>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>only active projects may be assigned</description>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Project Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000}</displayFormat>
        <label>Project Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectAssignmentServices.cls
public with sharing class ProjectAssignmentServices {
   public static Map<String, List<Project_Assignment__c>> 
    groupUniqueProjectAssigments(List<Project_Assignment__c> projects){
       
        Set<String> keysProjectDeveloper = new Set<String>();
        Map<String, List<Project_Assignment__c>> result = new Map<String, List<Project_Assignment__c>>();

            for(Project_Assignment__c recordAssignment : projects){
                String key = recordAssignment.Project__c+'-'+recordAssignment.Developer__c;
                if(result.keySet().contains(key)){
                 result.get(key).add(recordAssignment);
                }
                else {
                    List <Project_Assignment__c> projectAsSListNew = new List <Project_Assignment__c>();
                    projectAsSListNew.add(recordAssignment);
                    result.put(key,projectAsSListNew);
                }
            }
        return result;
    }
}
 
/*Create method groupUniqueProjectAssigments which should return map with Project_Assignment__c grouped 
by Projects and Developers.

Input parameter: List<Project_Assignment__c> projects

Result: Map<String, List<Project_Assignment__c>> - 
key is string representing Project_Assignment__c.Project__c + '-' + Project_Assignment__c.Developer__c,
 value - List Of Project_Assignment__c records;*/