Training Org Avenga/src/objects/Developer__c.object
<CustomObject>
    <description>The person who gets the job done</description>
    <fields>
        <fullName>Is_Billable__c</fullName>
        <description>if Dev has at least one billable project assigned - green image, else - yellow</description>
        <formula>IF(Total_Billable_Projects__c &gt;0,IMAGE(&quot;/resource/Green&quot;,&quot;Green&quot;,20,20),IMAGE(&quot;/resource/Yellow&quot;,&quot;Yellow&quot;,20,20))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Billable?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Billable_Projects__c</fullName>
        <description>Total number of active and billable projects</description>
        <label>Total Billable Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Developer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project__c.object
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <fields>
        <fullName>Is_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>defines if the project is billable (it happens)</description>
        <label>Is Billable?</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <description>dev</description>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>only active projects may be assigned</description>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Project Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000}</displayFormat>
        <label>Project Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Training Org Avenga/src/classes/Project_AssignmentTriggerHelper.cls
/**
 * Created by User on 18.10.2022.
 */

public with sharing class Project_AssignmentTriggerHelper {
    public static void beforeInsert(List<Project_Assignment__c> pas) {
        preventDuplicate(pas);
    }
    public static void beforeUpdate(List<Project_Assignment__c> pas) {
        preventDuplicate(pas);
    }
    public static void afterInsert(List<Project_Assignment__c> pas) {
        recalculateTotalBillableProjects(pas);
    }

    public static void preventDuplicate(List<Project_Assignment__c> pas) {

        Map<String, List<Project_Assignment__c>> mapAssignmentsNew = ProjectAssignmentServices.groupUniqueProjectAssignments(pas);
        List<Project_Assignment__c> filteredListPas = new List<Project_Assignment__c>();
        for (String key : mapAssignmentsNew.keySet()) {
            if (mapAssignmentsNew.get(key).size() > 1) {
                for (Project_Assignment__c el : mapAssignmentsNew.get(key)) {
                    el.addError('Duplicated Project assignment on the Developer in new list');
                }
            } else {
                filteredListPas.addAll(mapAssignmentsNew.get(key));
            }
        }
        if (filteredListPas.isEmpty()) {
            return ;
        }

        Set<Id> developerIds = new Set<Id>();
        Set<Id> projectIds = new Set<Id>();

        for (Project_Assignment__c pa : filteredListPas) {
            developerIds.add(pa.Developer__c);
            projectIds.add(pa.Project__c);
        }
        List<Project_Assignment__c> lPasOld = [
                SELECT Developer__c, Project__c
                FROM Project_Assignment__c
                WHERE Developer__c IN :developerIds
                AND Project__c IN :projectIds
        ];

        for (Project_Assignment__c paNew : filteredListPas) {
            for (Project_Assignment__c paOld : lPasOld) {
                if (paOld.Project__c == paNew.Project__c && paOld.Developer__c == paNew.Developer__c) {
                    paNew.addError('Duplicated Project assignment on the Developer');
                }
            }
        }
    }

    public static void recalculateTotalBillableProjects(List<Project_Assignment__c> pas) {

        Set <Id> developersIds = new Set<Id>();
        for (Project_Assignment__c pa : pas) {
            developersIds.add(pa.Developer__c);
        }

        List <Developer__c> developers = [
                SELECT Id, Total_Billable_Projects__c, (SELECT Id FROM Projects_Assignments__r WHERE Project__r.Is_Billable__c = TRUE)
                FROM Developer__c
                WHERE Id IN :developersIds
        ];

        for(Developer__c dev : developers){
            dev.Total_Billable_Projects__c = dev.Projects_Assignments__r.size();
        }
        update  developers;
    }
}