Training Org Avenga/src/objects/Developer__c.object
<CustomObject>
    <description>The person who gets the job done</description>
    <fields>
        <fullName>Is_Billable__c</fullName>
        <description>if Dev has at least one billable project assigned - green image, else - yellow</description>
        <formula>IF(Total_Billable_Projects__c &gt;0,IMAGE(&quot;/resource/Green&quot;,&quot;Green&quot;,20,20),IMAGE(&quot;/resource/Yellow&quot;,&quot;Yellow&quot;,20,20))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Billable?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Billable_Projects__c</fullName>
        <description>Total number of active and billable projects</description>
        <label>Total Billable Projects</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Developer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project__c.object
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <fields>
        <fullName>Is_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>defines if the project is billable (it happens)</description>
        <label>Is Billable?</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <description>dev</description>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>only active projects may be assigned</description>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Project Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000}</displayFormat>
        <label>Project Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Training Org Avenga/src/classes/Project_TriggerHelper.cls
/**
 * Created by User on 18.10.2022.
 */

public with sharing class Project_TriggerHelper {
    public static void afterUpdate(Map<Id, Project__c> newMap, Map<Id, Project__c> oldMap) {

        Set<Id> projectsWithChangedFieldTBP = new Set<Id>();

        for (Id key : newMap.keySet()) {
            if (oldMap.get(key).Is_Billable__c!= newMap.get(key).Is_Billable__c) {
                projectsWithChangedFieldTBP.add(key);
            }
        }
        updateTotalBillableProjects(projectsWithChangedFieldTBP);
    }
    public static void updateTotalBillableProjects(Set<Id> idProjectSet) {
        List<Project_Assignment__c> pas = [SELECT Developer__c FROM Project_Assignment__c WHERE Project__c IN :idProjectSet];

        Set <Id> developersIds = new Set<Id>();
        for (Project_Assignment__c pa : pas) {
            developersIds.add(pa.Developer__c);
        }
        List <Developer__c> developersToUpdate = new List<Developer__c>();

        Map<Id, Integer> totalBillableProjectField = ItCompanyDAO.getDeveloperTotalBillableProjects(developersIds);
        for (Id devId : totalBillableProjectField.keySet()) {
            developersToUpdate.add(new Developer__c(Id = devId, Total_Billable_Projects__c = totalBillableProjectField.get(devId)));
        }
        update developersToUpdate;
    }
}