Training Org Avenga/src/objects/Developer__c.object
<CustomObject>
    <description>The person who gets the job done</description>
    <label>Developer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project__c.object
<CustomObject>
    <description>Tasks client gives to company and developers do it. Task may consist of many devs. Same - one dev may be assigned to couple of projects at the same time.</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Training Org Avenga/src/objects/Project_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <description>dev</description>
        <label>Developer</label>
        <referenceTo>Developer__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>only active projects may be assigned</description>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects Assignments</relationshipLabel>
        <relationshipName>Projects_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Project Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000}</displayFormat>
        <label>Project Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Training Org Avenga/src/classes/DeveloperListAssignController.cls
/**
 * Created by User on 25.10.2022.
 */

public with sharing class DeveloperListAssignController {
    @AuraEnabled
    public static List<Project_Assignment__c> getProjectsAssignments(Id recordId) {
        List<Project_Assignment__c> listProjectAssignments = [
                SELECT Id,Name,CreatedDate,Project__r.Name
                FROM Project_Assignment__c
                WHERE Developer__c = :recordId
        ];
        return listProjectAssignments;
    }

}